 version: '3'
 services:
    nodejs:
        image: node_video_platform_api
        restart: always
        build: .
        ports:
            - 3000
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        volumes: ./db_video
        ports:
            - 5432
        environment: 
            - POSTGRES_PASSWORD=